import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/sass/_global.scss";
import { Analytics } from "@vercel/analytics/next";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: "Trattoria San Bernardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={`${montserrat.className}`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}